
package vistas;
import logica.Articulo;

public class ventana_principal extends javax.swing.JFrame {

    /**
     * Creates new form ventana_principal
     */
    
    carrito vtncarrito = null;
    Articulo[] articulos = new Articulo[10];
    int cont=0;
    double total=0;
    String pedido="";
    
    public ventana_principal() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carrito = new javax.swing.JButton();
        opciones = new javax.swing.JTabbedPane();
        ScrollPanequesos = new javax.swing.JScrollPane();
        Quesos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bq1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbq1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbq2 = new javax.swing.JComboBox<>();
        bq2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbq3 = new javax.swing.JComboBox<>();
        bq3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbq4 = new javax.swing.JComboBox<>();
        bq4 = new javax.swing.JButton();
        ScrollPaneaccesorios = new javax.swing.JScrollPane();
        accesorios = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cbacc2 = new javax.swing.JComboBox<>();
        bacc1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        cbacc1 = new javax.swing.JComboBox<>();
        bacc2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        cbacc3 = new javax.swing.JComboBox<>();
        bacc3 = new javax.swing.JButton();
        bacc4 = new javax.swing.JButton();
        cbacc4 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        ScrollPane_alacena = new javax.swing.JScrollPane();
        alacena = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ba1 = new javax.swing.JButton();
        cba1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cba2 = new javax.swing.JComboBox<>();
        ba2 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        cba3 = new javax.swing.JComboBox<>();
        ba3 = new javax.swing.JButton();
        ba4 = new javax.swing.JButton();
        cba4 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        ScrollPane_inicio = new javax.swing.JScrollPane();
        inicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtPedido = new javax.swing.JTextArea();
        Lbltotal = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        carrito.setBackground(new java.awt.Color(245, 242, 242));
        carrito.setFont(new java.awt.Font("Gill Sans MT Condensed", 0, 18)); // NOI18N
        carrito.setForeground(new java.awt.Color(102, 102, 0));
        carrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/compras.jpg"))); // NOI18N
        carrito.setText("Shopping bag");
        carrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carritoActionPerformed(evt);
            }
        });

        Quesos.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/1.jpg"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 0));
        jLabel7.setText("$176.00 MX");

        bq1.setBackground(new java.awt.Color(153, 153, 0));
        bq1.setForeground(new java.awt.Color(255, 255, 255));
        bq1.setText("Añadir");
        bq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bq1ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/2.jpg"))); // NOI18N

        cbq1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 0));
        jLabel10.setText("$184.00 MX");

        cbq2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        bq2.setBackground(new java.awt.Color(153, 153, 0));
        bq2.setForeground(new java.awt.Color(255, 255, 255));
        bq2.setText("Añadir");
        bq2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bq2ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/3.jpg"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 0));
        jLabel12.setText("$90.00 MX");

        cbq3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        bq3.setBackground(new java.awt.Color(153, 153, 0));
        bq3.setForeground(new java.awt.Color(255, 255, 255));
        bq3.setText("Añadir");
        bq3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bq3ActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/4.jpg"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 0));
        jLabel14.setText("$144.00 MX");

        cbq4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbq4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbq4ActionPerformed(evt);
            }
        });

        bq4.setBackground(new java.awt.Color(153, 153, 0));
        bq4.setForeground(new java.awt.Color(255, 255, 255));
        bq4.setText("Añadir");
        bq4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bq4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout QuesosLayout = new javax.swing.GroupLayout(Quesos);
        Quesos.setLayout(QuesosLayout);
        QuesosLayout.setHorizontalGroup(
            QuesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuesosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(QuesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(QuesosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(QuesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(QuesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cbq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(bq1)
                            .addComponent(cbq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bq2)
                            .addComponent(jLabel12)
                            .addComponent(cbq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bq3)
                            .addComponent(jLabel14)
                            .addComponent(cbq4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bq4))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        QuesosLayout.setVerticalGroup(
            QuesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuesosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel6)
                .addGroup(QuesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuesosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8))
                    .addGroup(QuesosLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bq1)))
                .addGap(42, 42, 42)
                .addGroup(QuesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(QuesosLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bq2)))
                .addGap(52, 52, 52)
                .addGroup(QuesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(QuesosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bq3)))
                .addGroup(QuesosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuesosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbq4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bq4)
                        .addGap(102, 102, 102))
                    .addGroup(QuesosLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        ScrollPanequesos.setViewportView(Quesos);

        opciones.addTab("Quesos", ScrollPanequesos);

        accesorios.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/ACC.jpg"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/8.jpg"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 153, 0));
        jLabel25.setText("$200.00 MXN");

        cbacc2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        bacc1.setBackground(new java.awt.Color(153, 153, 0));
        bacc1.setForeground(new java.awt.Color(255, 255, 255));
        bacc1.setText("Añadir");
        bacc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacc1ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 0));
        jLabel26.setText("$638.00 MXN");

        cbacc1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        bacc2.setBackground(new java.awt.Color(153, 153, 0));
        bacc2.setForeground(new java.awt.Color(255, 255, 255));
        bacc2.setText("Añadir");
        bacc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacc2ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 153, 0));
        jLabel27.setText("$398.00 MXN");

        cbacc3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        bacc3.setBackground(new java.awt.Color(153, 153, 0));
        bacc3.setForeground(new java.awt.Color(255, 255, 255));
        bacc3.setText("Añadir");
        bacc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacc3ActionPerformed(evt);
            }
        });

        bacc4.setBackground(new java.awt.Color(153, 153, 0));
        bacc4.setForeground(new java.awt.Color(255, 255, 255));
        bacc4.setText("Añadir");
        bacc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacc4ActionPerformed(evt);
            }
        });

        cbacc4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 0));
        jLabel28.setText("$298.00 MXN");

        javax.swing.GroupLayout accesoriosLayout = new javax.swing.GroupLayout(accesorios);
        accesorios.setLayout(accesoriosLayout);
        accesoriosLayout.setHorizontalGroup(
            accesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accesoriosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(accesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(accesoriosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(accesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(cbacc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bacc1)
                            .addComponent(bacc2)
                            .addComponent(cbacc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addComponent(cbacc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bacc3)
                            .addComponent(bacc4)
                            .addComponent(cbacc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accesoriosLayout.setVerticalGroup(
            accesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accesoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGroup(accesoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accesoriosLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbacc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(bacc1)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbacc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bacc2)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbacc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bacc3)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbacc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bacc4))
                    .addGroup(accesoriosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ScrollPaneaccesorios.setViewportView(accesorios);

        opciones.addTab("Accesorios", ScrollPaneaccesorios);

        alacena.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/ala.jpg"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/5.jpg"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/6.jpg"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/7.jpg"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 0));
        jLabel19.setText("$80.00MXN");

        ba1.setBackground(new java.awt.Color(153, 153, 0));
        ba1.setForeground(new java.awt.Color(255, 255, 255));
        ba1.setText("Agregar");
        ba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ba1ActionPerformed(evt);
            }
        });

        cba1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 0));
        jLabel20.setText("$70.00MXN");

        cba2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        ba2.setBackground(new java.awt.Color(153, 153, 0));
        ba2.setForeground(new java.awt.Color(255, 255, 255));
        ba2.setText("Agregar");
        ba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ba2ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 0));
        jLabel21.setText("$33.80MXN");

        cba3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        ba3.setBackground(new java.awt.Color(153, 153, 0));
        ba3.setForeground(new java.awt.Color(255, 255, 255));
        ba3.setText("Agregar");
        ba3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ba3ActionPerformed(evt);
            }
        });

        ba4.setBackground(new java.awt.Color(153, 153, 0));
        ba4.setForeground(new java.awt.Color(255, 255, 255));
        ba4.setText("Agregar");
        ba4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ba4ActionPerformed(evt);
            }
        });

        cba4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 0));
        jLabel22.setText("$33.80MXN");

        javax.swing.GroupLayout alacenaLayout = new javax.swing.GroupLayout(alacena);
        alacena.setLayout(alacenaLayout);
        alacenaLayout.setHorizontalGroup(
            alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alacenaLayout.createSequentialGroup()
                .addGroup(alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alacenaLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(alacenaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(42, 42, 42)
                                .addGroup(alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ba1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel21)
                                                .addComponent(cba2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel19)))
                            .addGroup(alacenaLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(43, 43, 43)
                                .addGroup(alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ba2)
                                    .addComponent(ba4)
                                    .addComponent(cba4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alacenaLayout.createSequentialGroup()
                                .addGroup(alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ba3)
                                    .addComponent(cba3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))))
                    .addGroup(alacenaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        alacenaLayout.setVerticalGroup(
            alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alacenaLayout.createSequentialGroup()
                .addGroup(alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alacenaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel16)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17))
                    .addGroup(alacenaLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ba1)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cba2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ba2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(alacenaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(alacenaLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cba3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ba3)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cba4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ba4))
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ScrollPane_alacena.setViewportView(alacena);

        opciones.addTab("Alacena", ScrollPane_alacena);

        inicio.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("QUE SABOR.");

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 3, 36)); // NOI18N
        jLabel2.setText("De mazamitla a tu casa.");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/inicio.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/Captura de pantalla 2022-05-22 184455.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/a.jpg"))); // NOI18N

        javax.swing.GroupLayout inicioLayout = new javax.swing.GroupLayout(inicio);
        inicio.setLayout(inicioLayout);
        inicioLayout.setHorizontalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel2))
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(inicioLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inicioLayout.setVerticalGroup(
            inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(39, 39, 39))
        );

        ScrollPane_inicio.setViewportView(inicio);

        opciones.addTab("Inicio", ScrollPane_inicio);

        jLabel29.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 153, 0));
        jLabel29.setText("QUE SABOR.");

        txtPedido.setEditable(false);
        txtPedido.setColumns(20);
        txtPedido.setRows(5);
        jScrollPane5.setViewportView(txtPedido);

        Lbltotal.setBackground(new java.awt.Color(153, 153, 0));
        Lbltotal.setFont(new java.awt.Font("Myanmar Text", 1, 18)); // NOI18N
        Lbltotal.setForeground(new java.awt.Color(255, 255, 255));
        Lbltotal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel30.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(153, 153, 0));
        jLabel30.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(carrito)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(39, 39, 39)
                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(carrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bq1ActionPerformed
        articulos[cont]=agregar_art(cbq1.getSelectedIndex()+1,"Queso de oveja tierno sin lactosa",176.00);
        ver_pedido();
    }//GEN-LAST:event_bq1ActionPerformed

    private void bq2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bq2ActionPerformed
         articulos[cont]=agregar_art(cbq2.getSelectedIndex()+1,"Queso de oveja tierno sin lactosa con pimienta rosa",184.00);
        ver_pedido();
    }//GEN-LAST:event_bq2ActionPerformed

    private void bq3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bq3ActionPerformed
         articulos[cont]=agregar_art(cbq3.getSelectedIndex()+1,"Requeson",90.00);
        ver_pedido();
    }//GEN-LAST:event_bq3ActionPerformed

    private void bq4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bq4ActionPerformed
         articulos[cont]=agregar_art(cbq4.getSelectedIndex()+1,"Queso de oveja tierno en aceite  quesalado",144.00);
        ver_pedido();
    }//GEN-LAST:event_bq4ActionPerformed

    private void carritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carritoActionPerformed
        if(vtncarrito==null){
            vtncarrito = new carrito(this,pedido,total);
        }
        vtncarrito.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_carritoActionPerformed

    private void cbq4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbq4ActionPerformed

    }//GEN-LAST:event_cbq4ActionPerformed

    private void bacc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacc1ActionPerformed
         articulos[cont]=agregar_art(cbacc1.getSelectedIndex()+1,"Botella de cristal Summum 2020",200.00);
        ver_pedido();
    }//GEN-LAST:event_bacc1ActionPerformed

    private void bacc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacc2ActionPerformed
         articulos[cont]=agregar_art(cbacc2.getSelectedIndex()+1,"Fondue para queso Boska set Non-Stick",638.00);
        ver_pedido();
    }//GEN-LAST:event_bacc2ActionPerformed

    private void bacc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacc3ActionPerformed
         articulos[cont]=agregar_art(cbacc3.getSelectedIndex()+1,"Fondue para quesos Tapas Grey",398.00);
        ver_pedido();
    }//GEN-LAST:event_bacc3ActionPerformed

    private void bacc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacc4ActionPerformed
         articulos[cont]=agregar_art(cbacc4.getSelectedIndex()+1,"Fondue tapas Gouda",298.00);
        ver_pedido();
    }//GEN-LAST:event_bacc4ActionPerformed

    private void ba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ba1ActionPerformed
        articulos[cont]=agregar_art(cba1.getSelectedIndex()+1,"Chocolate artesano con queso",80.00);
        ver_pedido();
    }//GEN-LAST:event_ba1ActionPerformed

    private void ba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ba2ActionPerformed
        articulos[cont]=agregar_art(cba2.getSelectedIndex()+1,"Chocolate negro 70% con yougur y frambuesa",70.00);
        ver_pedido();
    }//GEN-LAST:event_ba2ActionPerformed

    private void ba3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ba3ActionPerformed
         articulos[cont]=agregar_art(cba3.getSelectedIndex()+1,"Salsa para queso de manzana Golden y pisachos 70g",33.80);
        ver_pedido();
    }//GEN-LAST:event_ba3ActionPerformed

    private void ba4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ba4ActionPerformed
         articulos[cont]=agregar_art(cba4.getSelectedIndex()+1,"Salsa para queso de melocoton y albaricoque 70g",33.80);
        ver_pedido();
    }//GEN-LAST:event_ba4ActionPerformed

    public Articulo agregar_art(int cantidad, String nombre, double precio){
        Articulo art = new Articulo();
        art.setCantidad(cantidad);
        art.setNombre(nombre);
        art.setPrecio(precio);
        art.setSubtotal();
        total += art.getSubtotal();
      //total = total + art.getSubtotal();  
        cont++;
        return art;
    }
    
    public void ver_pedido(){
        txtPedido.setText("");
        System.out.println(cont);
        pedido="Cant  Descripcion\n";
        //txtPedido.setText("Cantidad  Descripcion  Precio  Subtotal\n");
        for (int i = 0; i < cont; i++) {
            pedido += (articulos[i].getCantidad()+"   "+articulos[i].getNombre()+"\n\t$"+articulos[i].getPrecio()+"\t$"+articulos[i].getSubtotal()+"\n");
        }
        txtPedido.setText(pedido);
        Lbltotal.setText("$"+Double.toString(total));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbltotal;
    private javax.swing.JPanel Quesos;
    private javax.swing.JScrollPane ScrollPane_alacena;
    private javax.swing.JScrollPane ScrollPane_inicio;
    private javax.swing.JScrollPane ScrollPaneaccesorios;
    private javax.swing.JScrollPane ScrollPanequesos;
    private javax.swing.JPanel accesorios;
    private javax.swing.JPanel alacena;
    private javax.swing.JButton ba1;
    private javax.swing.JButton ba2;
    private javax.swing.JButton ba3;
    private javax.swing.JButton ba4;
    private javax.swing.JButton bacc1;
    private javax.swing.JButton bacc2;
    private javax.swing.JButton bacc3;
    private javax.swing.JButton bacc4;
    private javax.swing.JButton bq1;
    private javax.swing.JButton bq2;
    private javax.swing.JButton bq3;
    private javax.swing.JButton bq4;
    private javax.swing.JButton carrito;
    private javax.swing.JComboBox<String> cba1;
    private javax.swing.JComboBox<String> cba2;
    private javax.swing.JComboBox<String> cba3;
    private javax.swing.JComboBox<String> cba4;
    private javax.swing.JComboBox<String> cbacc1;
    private javax.swing.JComboBox<String> cbacc2;
    private javax.swing.JComboBox<String> cbacc3;
    private javax.swing.JComboBox<String> cbacc4;
    private javax.swing.JComboBox<String> cbq1;
    private javax.swing.JComboBox<String> cbq2;
    private javax.swing.JComboBox<String> cbq3;
    private javax.swing.JComboBox<String> cbq4;
    private javax.swing.JPanel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane opciones;
    private javax.swing.JTextArea txtPedido;
    // End of variables declaration//GEN-END:variables
}
